name: vtools
version: '1.0'
summary: python test package
description: |
 test app for python
base: core18
grade: stable
confinement: strict

apps:
  vtools:
    command: bin/vtools
    plugs: [home,network-bind]

parts:
  vtools:
    plugin: python
    python-version: python3
    source: .
    stage-packages: [ncbi-blast+, virtualbox]
    build-packages: [virtualbox]
    python-packages:
      - requests
      - tabular-log
