name: vtools
version: '1.0'
summary: python test package
description: |
 test app for python
base: core18
grade: stable
confinement: strict

apps:
  vtools:
    command: bin/vtools
    plugs: [home,network-bind]

parts:
  virtualbox:
    source: https://download.virtualbox.org/virtualbox/6.1.18/virtualbox-6.1_6.1.18-142142~Ubuntu~eoan_amd64.deb
    plugin: virtualbox
    source-type: deb
    override-build: |
      snapcraftctl build
    stage-packages:
      - virtualbox
    after: [vtools]

  vtools:
    plugin: python
    python-version: python3
    source: .
    stage-packages: [ncbi-blast+]
    python-packages:
      - requests
      - tabular-log
