.\" This man page for vtools
.TH vtools "1" "2021-03-20" "vtools 01.06" "User Commands"
.SH NAME
vtools
.SH SYNOPSIS
.B vtools - get virtal machines infos
.br
.B vtools [--batch | -b] - disable GUI mode
.br
.B vtools [--verbose] - verbose mode (if not in GUI mode)
.br
.B vtools [--csv] - enable csv output (if not in GUI mode)
.br
.B vtools [--url=... --token=... --OStable=... --NETtable=...] - enable the upload to HarperDB (Replace "..." with the value(s)) (if not in GUI mode)
.br
.SH DESCRIPTION
Manage vitual machines, getting some informations (eg. OS).
.SH AUTHORS
Castellani Davide: owner