name: Test snap on every push

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi
        sudo apt install snapd tree
        sudo snap install --classic snapcraft
        sudo snap install multipass
        multipass launch --name foo
        multipass exec foo -- lsb_release -a
    - name: Build snap
      run: |
        snapcraft
    - name: Check files
      run: |
        tree
        